print("Time1")
h1=int(input("ENter the hour"))
m1=int(input("Enter the minutes"))
s1=int(input("Enter the seconds"))
seconds1=(h1*3600)+(m1*60)+(s1)
print(seconds1)
print("Time2")
h2=int(input("Enter the hour"))
m2=int(input("Enter the min"))
s2=int(input("Enter the seconds"))
seconds2=(h2*3600)+(m2*60)+(s2)
print(seconds2)
totsec=seconds1-seconds2
print(totsec)
